#python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/A/source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector &
#python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/A/source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

#wait

#python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/C/source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/C_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector &
#python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/C/source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/C_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

#wait

python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/P/source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/P_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector &
python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/P/source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/P_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

wait

python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/R/source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector &
python combined.py --dataset decision_office_home --batch_size 64 --model_name resnet50 --model_path data/decision/office-home/R/source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method decision_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 256 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_decision.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector


