python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/CA/finetuned_source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/PA/finetuned_source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/RA/finetuned_source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/CR/finetuned_source_B.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/CR/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/CA/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/PA/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python3 combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/RA/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method dine_office_home --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/A_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector
