python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/AC/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/C_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/PC/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/C_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/RC/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/C_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/AP/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/P_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/CP/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/P_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/RP/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/P_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/AR/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

python combined.py --dataset dine_office_home --batch_size 64 --model_name resnet50 --model_path data/dine/office_home/resnet50/PR/finetuned_source_B.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks auto_attack --method dine_office_home --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10 --ent_par 0.8 --cls_par 0.3  --dataset_path clean_data/OfficeHome/R_list.txt --correction_batch_size 400 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_dine.txt --pop 1 --use_wandb --recreate_adv_data --retrain_detector

