#python combined.py --dataset cifar10 --batch_size 32 --model_name resnet18 --model_path data/source/cifar10/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method vanila --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb &
#python combined.py --dataset cifar10 --batch_size 32 --model_name resnet18 --model_path data/source/cifar10/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd auto_attack --method vanila --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb &
#python combined.py --dataset cifar10 --batch_size 32 --model_name resnet18 --model_path data/source/cifar10/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method vanila --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb 

#wait 

#python combined.py --dataset svhn --batch_size 32 --model_name resnet18 --model_path data/source/svhn/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method vanila --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb &
#python combined.py --dataset svhn --batch_size 32 --model_name resnet18 --model_path data/source/svhn/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd auto_attack --method vanila --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb &
#python combined.py --dataset svhn --batch_size 32 --model_name resnet18 --model_path data/source/svhn/resnet18/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method vanila --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 256 --r_range 16 --soft_detection_r 32 --log_path ./logs/logs_imbalanced.txt --pop 10 --retrain_detector --recreate_adv_data --use_wandb 


#wait

python combined.py --dataset cub --batch_size 64 --model_name resnet34 --model_path data/source/cub/resnet34/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method vanila --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 32 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_imbalanced.txt --pop 1 --retrain_detector  --use_wandb &
python combined.py --dataset cub --batch_size 64 --model_name resnet34 --model_path data/source/cub/resnet34/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd auto_attack --method vanila --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 32 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_imbalanced.txt --pop 1 --retrain_detector  --use_wandb &
python combined.py --dataset cub --batch_size 64 --model_name resnet34 --model_path data/source/cub/resnet34/net.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks auto_attack --method vanila --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist --ent_par 0.8 --cls_par 0.3 --correction_batch_size 32 --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_imbalanced.txt --pop 1 --retrain_detector --use_wandb 


