python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AD/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt & 

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AD/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AD/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait


python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AD/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AW/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AW/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait



python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AW/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/AW/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DA/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait


python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DA/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DA/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DA/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WA/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WA/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WA/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 


wait

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WA/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/amazon.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DW/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DW/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DW/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/DW/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/webcam.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WD/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt 

wait

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WD/target_B_par_0.3.pt --detector_path data/source/fmnist/resnet18/fmnist_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 0 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset fmnist   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WD/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 1 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &

python3 combined.py --dataset shot_office  --batch_size 64  --model_name resnet50  --model_path data/shot_office/WD/target_B_par_0.3.pt --detector_path data/source/cifar10/resnet18/cifar10_pgd_seed_0_source_detector.pt --attacks pgd --method shot_office --gpu 2 --droprate 0.005 --seed 0 --lr 0.005 --epochs 10 --s_dataset cifar10   --ent_par 0.8  --cls_par 0.3 --recreate_adv_data --retrain_detector --dataset_path clean_data/office/dslr.txt --correction_batch_size 16 --use_wandb --r_range 112 --soft_detection_r 224 --log_path ./logs/logs_shot.txt &
